rem ************ Nome: Davi Augusto Neves Leite ******************
rem ************ RA: 191027383                  ******************

rem **************** SGBD: Oracle SQL ***********************

rem Pré-requisitos: criação e população da tabela 'Funcionários'

create table Funcionario(
  rg number(2) generated by default on null as identity primary key,
  nome varchar2(50) not null,
  endereco varchar2(100) not null,
  salario number(10,2) not null,
  departamento varchar2(50) not null,
  funcao varchar2(50) not null
);

rem Transação 1: inserir e retornar os novos dados da tabela Funcionário (operação de escrita e leitura)
set transaction read write;

insert into Funcionario (nome, endereco, salario, departamento, funcao)
values ('Davi', 'Rua Não Sei', ROUND(DBMS_RANDOM.VALUE(1, 10000)), 'Computação', 'Aluno');

select * from Funcionario;

commit;

rem Transação 2: atualizar e retornar os novos dados da tabela Funcionário (operação de escrita e leitura)
set transaction read write;

select * from Funcionario;

update Funcionario
set
    nome = 'Nilceu Marana',
    endereco = 'Rua Continuo Não Sabendo',
    salario = ROUND(DBMS_RANDOM.VALUE(1, 10000)),
    funcao = 'Professor'
where exists
    (select rg from Funcionario
     where nome = 'Davi');

select * from Funcionario;

rollback;
