# MPLAB IDE generated this makefile for use with GNU make.
# Project: CronometroComControle.mcp
# Date: Sun Nov 08 00:23:32 2020

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

CronometroComControle.cof : CronometroComControle.o
	$(CC) /p16F873 "CronometroComControle.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"CronometroComControle.cof" /M"CronometroComControle.map" /W /x

CronometroComControle.o : CronometroComControle.asm ../../../../../../../../Programas/Microcontroladores/Microchip/MPASM\ Suite/p16f628a.inc
	$(AS) /q /p16F873 "CronometroComControle.asm" /l"CronometroComControle.lst" /e"CronometroComControle.err" /d__DEBUG=1

clean : 
	$(CC) "CronometroComControle.o" "CronometroComControle.hex" "CronometroComControle.err" "CronometroComControle.lst" "CronometroComControle.cof"

