# MPLAB IDE generated this makefile for use with GNU make.
# Project: ADCeSerial.mcp
# Date: Sun Nov 29 14:57:09 2020

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

ADCeSerial.cof : ADCeSerial.o
	$(CC) /p16F873 "ADCeSerial.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"ADCeSerial.cof" /M"ADCeSerial.map" /W /x

ADCeSerial.o : ADCeSerial.asm ../../../../../../../../Programas/Microcontroladores/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F873 "ADCeSerial.asm" /l"ADCeSerial.lst" /e"ADCeSerial.err" /d__DEBUG=1

clean : 
	$(CC) "ADCeSerial.o" "ADCeSerial.hex" "ADCeSerial.err" "ADCeSerial.lst" "ADCeSerial.cof"

